import { productImages } from './productImages';

export const mockProducts = [
  // Electronics & Tech
  {
    id: 'prod-001',
    name: '1080p Full HD Webcam with Mic',
    category: 'Electronics',
    price: 49.99,
    rating: 4.5,
    stock: 25,
    image: productImages.webcam,
    description: 'High-definition video webcam with integrated noise-reducing microphone for streaming and calls.',
  },
  {
    id: 'prod-002',
    name: '4K Ultra HD Smart TV 55"',
    category: 'Electronics',
    price: 499.99,
    rating: 4.8,
    stock: 10,
    image: productImages.tv4k,
    description: 'Immersive 4K visual display with built-in streaming apps and voice control support.',
  },
  {
    id: 'prod-003',
    name: 'Apple iPad Air',
    category: 'Electronics',
    price: 599.00,
    rating: 4.9,
    stock: 15,
    image: productImages.ipadAir,
    description: 'Lightweight tablet featuring liquid Retina display, M-series processor, and all-day battery life.',
  },
  {
    id: 'prod-004',
    name: 'Asus Vivobook 14',
    category: 'Electronics',
    price: 429.99,
    rating: 4.3,
    stock: 12,
    image: productImages.asusLaptop,
    description: 'Compact 14-inch laptop optimized for productivity and everyday computing tasks.',
  },
  {
    id: 'prod-005',
    name: 'Dell Vostro 3420',
    category: 'Electronics',
    price: 549.50,
    rating: 4.4,
    stock: 8,
    image: productImages.dellLaptop,
    description: 'Business-class laptop with enhanced security features and reliable processing speed.',
  },
  {
    id: 'prod-006',
    name: 'Dual-Band Wi-Fi 6 Router',
    category: 'Electronics',
    price: 89.99,
    rating: 4.6,
    stock: 30,
    image: productImages.wifiRouter,
    description: 'Next-generation network router delivering high-speed internet connectivity across multiple devices.',
  },
  {
    id: 'prod-007',
    name: '1TB External Solid State Drive',
    category: 'Electronics',
    price: 119.99,
    rating: 4.7,
    stock: 40,
    image: productImages.externalSsd,
    description: 'Ultra-fast portable SSD storage drive with shock-resistant durable casing.',
  },
  {
    id: 'prod-008',
    name: 'Full HD Home Theater Projector',
    category: 'Electronics',
    price: 210.00,
    rating: 4.2,
    stock: 14,
    image: productImages.hdProjector,
    description: 'High-lumens video projector suitable for cinema-quality indoor and outdoor projections.',
  },
  {
    id: 'prod-009',
    name: 'Graphics Drawing Tablet',
    category: 'Electronics',
    price: 75.00,
    rating: 4.5,
    stock: 18,
    image: productImages.drawingTablet,
    description: 'Ergonomic pressure-sensitive digital drawing pad for illustrators and designers.',
  },
  {
    id: 'prod-010',
    name: 'HP Pavilion 15',
    category: 'Electronics',
    price: 679.99,
    rating: 4.6,
    stock: 9,
    image: productImages.hpLaptop,
    description: '15.6-inch laptop offering micro-edge display visuals and audio tuned by B&O.',
  },
  {
    id: 'prod-011',
    name: 'Mechanical Gaming Keyboard',
    category: 'Electronics',
    price: 64.99,
    rating: 4.7,
    stock: 22,
    image: productImages.mechanicalKeyboard,
    description: 'RGB backlit mechanical keyboard equipped with tactile switches for precision gaming.',
  },
  {
    id: 'prod-012',
    name: 'Noise Cancelling Earbuds',
    category: 'Electronics',
    price: 129.99,
    rating: 4.8,
    stock: 35,
    image: productImages.noiseEarbuds,
    description: 'True wireless stereo earbuds featuring active noise cancellation and IPX5 water resistance.',
  },
  {
    id: 'prod-013',
    name: 'Portable Bluetooth Speaker',
    category: 'Electronics',
    price: 39.99,
    rating: 4.4,
    stock: 50,
    image: productImages.bluetoothSpeaker,
    description: 'Waterproof wireless speaker with deep bass output and 12-hour continuous playback.',
  },
  {
    id: 'prod-014',
    name: 'Professional DSLR Camera',
    category: 'Electronics',
    price: 899.00,
    rating: 4.9,
    stock: 5,
    image: productImages.dslrCamera,
    description: 'High-resolution digital SLR camera package including interchangeable lens kit.',
  },
  {
    id: 'prod-015',
    name: 'Streaming Condenser Microphone',
    category: 'Electronics',
    price: 59.99,
    rating: 4.6,
    stock: 20,
    image: productImages.streamingMic,
    description: 'USB cardioid studio condenser microphone for podcasts, vocals, and voiceovers.',
  },
  {
    id: 'prod-016',
    name: 'Wireless Gaming Mouse',
    category: 'Electronics',
    price: 45.00,
    rating: 4.5,
    stock: 28,
    image: productImages.wirelessMouse,
    description: 'Ultra-lightweight optical gaming mouse featuring programmable buttons and high DPI tracking.',
  },

  // Home & Kitchen
  {
    id: 'prod-017',
    name: 'Air Purifier for Home',
    category: 'Home & Kitchen',
    price: 99.99,
    rating: 4.6,
    stock: 16,
    image: productImages.airPurifier,
    description: 'HEPA air filtration system designed to eliminate allergens, dust, and airborne odors.',
  },
  {
    id: 'prod-018',
    name: 'Aromatic Reed Diffuser Set',
    category: 'Home & Kitchen',
    price: 24.50,
    rating: 4.3,
    stock: 45,
    image: productImages.reedDiffuser,
    description: 'Long-lasting essential oil glass reed diffuser set for subtle home fragrance.',
  },
  {
    id: 'prod-019',
    name: 'Pre-Seasoned Cast Iron Skillet',
    category: 'Home & Kitchen',
    price: 29.99,
    rating: 4.8,
    stock: 30,
    image: productImages.castIronSkillet,
    description: 'Heavy-duty 10.25-inch cast iron pan with optimal heat retention for searing and baking.',
  },
  {
    id: 'prod-020',
    name: 'Ceramic Succulent Pots (Set of 3)',
    category: 'Home & Kitchen',
    price: 19.99,
    rating: 4.7,
    stock: 60,
    image: productImages.succulentPots,
    description: 'Decorative mini ceramic planter pots with drainage holes and bamboo coasters.',
  },
  {
    id: 'prod-021',
    name: 'Digital Kitchen Scale',
    category: 'Home & Kitchen',
    price: 14.99,
    rating: 4.5,
    stock: 40,
    image: productImages.kitchenScale,
    description: 'Precision food scale with LCD display and multi-unit weight measurement.',
  },
  {
    id: 'prod-022',
    name: 'Handheld Electric Milk Frother',
    category: 'Home & Kitchen',
    price: 12.99,
    rating: 4.4,
    stock: 50,
    image: productImages.milkFrother,
    description: 'Battery-operated foam maker for lattes, cappuccinos, and matcha whisking.',
  },
  {
    id: 'prod-023',
    name: 'Sonic Electric Toothbrush',
    category: 'Home & Kitchen',
    price: 39.99,
    rating: 4.6,
    stock: 22,
    image: productImages.electricToothbrush,
    description: 'Rechargeable electric toothbrush featuring 5 operational modes and smart timer.',
  },
  {
    id: 'prod-024',
    name: 'Ergonomic Mesh Office Chair',
    category: 'Home & Kitchen',
    price: 159.99,
    rating: 4.5,
    stock: 11,
    image: productImages.officeChair,
    description: 'Adjustable lumbar support desk chair constructed with breathable mesh backrest.',
  },
  {
    id: 'prod-025',
    name: 'Gourmet Knife Block Set (6-Piece)',
    category: 'Home & Kitchen',
    price: 79.99,
    rating: 4.7,
    stock: 13,
    image: productImages.knifeBlockSet,
    description: 'Stainless steel kitchen knife collection stored in an hardwood storage block.',
  },
  {
    id: 'prod-026',
    name: 'Dimmable LED Desk Lamp',
    category: 'Home & Kitchen',
    price: 27.99,
    rating: 4.6,
    stock: 35,
    image: productImages.ledLamp,
    description: 'Touch-controlled table lamp equipped with USB charging port and multiple brightness levels.',
  },
  {
    id: 'prod-027',
    name: 'Memory Foam Contour Pillow',
    category: 'Home & Kitchen',
    price: 34.99,
    rating: 4.4,
    stock: 27,
    image: productImages.memoryPillow,
    description: 'Ergonomic cervical support pillow designed to relieve neck and shoulder pressure.',
  },
  {
    id: 'prod-028',
    name: 'Non-Stick Cookware Set (10-Piece)',
    category: 'Home & Kitchen',
    price: 119.00,
    rating: 4.6,
    stock: 10,
    image: productImages.cookwareSet,
    description: 'Aluminum pots and pans set featuring durable scratch-resistant non-stick coating.',
  },
  {
    id: 'prod-029',
    name: 'Programmable Premium Coffee Maker',
    category: 'Home & Kitchen',
    price: 69.99,
    rating: 4.5,
    stock: 19,
    image: productImages.coffeeMaker,
    description: '12-cup drip coffee machine with auto-brew timer and strength control settings.',
  },
  {
    id: 'prod-030',
    name: 'Smart Fitness Tracker Watch',
    category: 'Electronics',
    price: 49.99,
    rating: 4.3,
    stock: 33,
    image: productImages.fitnessWatch,
    description: 'Activity tracker featuring heart rate monitor, sleep tracking, and step counter.',
  },
  {
    id: 'prod-031',
    name: 'Smart LED Light Bulb (Color Changing)',
    category: 'Home & Kitchen',
    price: 15.99,
    rating: 4.5,
    stock: 45,
    image: productImages.smartBulb,
    description: 'Wi-Fi enabled dimmable RGB LED bulb compatible with Alexa and Google Assistant.',
  },

  // Fashion & Accessories
  {
    id: 'prod-032',
    name: 'Classic Aviator Sunglasses',
    category: 'Fashion',
    price: 22.00,
    rating: 4.4,
    stock: 40,
    image: productImages.aviatorSunglasses,
    description: 'Metal frame aviator sunglasses providing UV400 glare protection.',
  },
  {
    id: 'prod-033',
    name: 'Canvas Crossbody Shoulder Bag',
    category: 'Fashion',
    price: 29.99,
    rating: 4.5,
    stock: 25,
    image: productImages.crossbodyBag,
    description: 'Casual multi-zipper canvas satchel bag designed for daily travel and commuting.',
  },
  {
    id: 'prod-034',
    name: 'Canvas Slip-On Sneakers',
    category: 'Fashion',
    price: 35.00,
    rating: 4.3,
    stock: 30,
    image: productImages.slipOnSneakers,
    description: 'Low-profile casual slip-on footwear constructed with durable canvas uppers.',
  },
  {
    id: 'prod-035',
    name: 'Genuine Leather Men\'s Bifold Wallet',
    category: 'Fashion',
    price: 24.99,
    rating: 4.7,
    stock: 50,
    image: productImages.mensWallet,
    description: 'Slim genuine leather wallet featuring RFID blocking material and multiple card slots.',
  },
  {
    id: 'prod-036',
    name: 'Men\'s Casual Denim Jacket',
    category: 'Fashion',
    price: 59.99,
    rating: 4.6,
    stock: 15,
    image: productImages.denimJacket,
    description: 'Classic button-down denim trucker jacket with dual chest flap pockets.',
  },
  {
    id: 'prod-037',
    name: 'Men\'s Slim Fit Chinos',
    category: 'Fashion',
    price: 39.99,
    rating: 4.4,
    stock: 28,
    image: productImages.slimChinos,
    description: 'Stretch cotton casual trouser pants designed for a tailored fit.',
  },
  {
    id: 'prod-038',
    name: 'Microfiber Bath Towels (Set of 4)',
    category: 'Home & Kitchen',
    price: 26.99,
    rating: 4.6,
    stock: 35,
    image: productImages.bathTowels,
    description: 'Quick-drying, absorbent microfiber bath sheets for home and gym use.',
  },
  {
    id: 'prod-039',
    name: 'Minimalist Leather Backpack',
    category: 'Fashion',
    price: 85.00,
    rating: 4.8,
    stock: 12,
    image: productImages.leatherBackpack,
    description: 'Sleek leather laptop backpack suitable for business and urban travel.',
  },
  {
    id: 'prod-040',
    name: 'Polarized Sports Sunglasses',
    category: 'Fashion',
    price: 25.99,
    rating: 4.5,
    stock: 30,
    image: productImages.sportsSunglasses,
    description: 'Wrap-around lightweight polarized sunglasses for cycling, running, and driving.',
  },
  {
    id: 'prod-041',
    name: 'Unisex Cotton Fleece Hoodie',
    category: 'Fashion',
    price: 42.50,
    rating: 4.7,
    stock: 20,
    image: productImages.cottonHoodie,
    description: 'Soft fleece-lined pullover hoodie featuring kangaroo pouch pocket.',
  },
  {
    id: 'prod-042',
    name: 'Women\'s Rose Gold Analogue Watch',
    category: 'Fashion',
    price: 75.00,
    rating: 4.6,
    stock: 18,
    image: productImages.womensWatch,
    description: 'Minimalist analogue wristwatch designed with a mesh stainless steel strap.',
  },
  {
    id: 'prod-043',
    name: 'Women\'s Leather Tote Shoulder Bag',
    category: 'Fashion',
    price: 65.00,
    rating: 4.7,
    stock: 14,
    image: productImages.leatherToteBag,
    description: 'Spacious everyday tote bag featuring inner zip organizer compartments.',
  },
  {
    id: 'prod-044',
    name: 'Women\'s Athletic Running Shorts',
    category: 'Fashion',
    price: 21.99,
    rating: 4.4,
    stock: 40,
    image: productImages.runningShorts,
    description: 'Lightweight, breathable workout shorts with elastic waistband and phone pocket.',
  },
  {
    id: 'prod-045',
    name: 'Lightweight Athletic Running Shoes',
    category: 'Fashion',
    price: 54.99,
    rating: 4.5,
    stock: 22,
    image: productImages.runningShoes,
    description: 'Cushioned mesh road running sneakers engineered for high impact absorption.',
  },
];